# Generated by Django 3.2.9 on 2022-01-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePwd',
        ),
    ]
