# Generated by Django 3.2.9 on 2022-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220101_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='lastPasswords',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='resetCode',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
