# Generated by Django 3.2.9 on 2022-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220101_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='resetCode',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
    ]
