# Generated by Django 3.2.9 on 2022-01-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usersdata_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='resetCode',
            field=models.CharField(blank=True, default='', max_length=40, null=True, unique=True),
        ),
    ]
